[package]
name = "CryptocurrencyBacktester"
version = "0.1.0"
edition = "2021"

[dependencies]
strum_macros = "0.26.4"
strum = "0.26.3"
serde = { version = "1.0.210", features = ["derive"] }
csv = "1.3.0"
serde_json = "1.0.128"
